openapi: 3.0.0

info:
  title: vega-it-minimal-demo
  version: 0.3.0
  description: "This is an example OpenAPI specification"
  termsOfService: "http://example.com/tos"
  contact:
    email: "example@example.com"
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params:
    validateRequestBody: true
    validateRequestParameters: true
  body:
    validateRequestBody: true
    validateRequestParameters: false

paths:
 
   /api/{tenant_id}/hello/{name}:
    get:
      operationId: hello
      description: Test sam local functionality with API Gateway & Open API
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 3000
        type: "aws_proxy"
      responses:
        '200':
          description: A 200 response.
          content:
            application/json:
              schema:
                type: object
        '400':
          description: bad input parameter

   /hello:
    get:
      operationId: hello
      description: Test sam local functionality with API Gateway & Open API
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 3000
        type: "aws_proxy"
      responses:
        '200':
          description: A 200 response.
          content:
            application/json:
              schema:
                type: object
        '400':
          description: bad input parameter
   /hello/{name}:
    get:
      operationId: hello
      description: Test sam local functionality with API Gateway & Open API
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 3000
        type: "aws_proxy"
      responses:
        '200':
          description: A 200 response.
          content:
            application/json:
              schema:
                type: object
        '400':
          description: bad input parameter
   /good-bye:
    get:
      operationId: goodbye
      description: Test sam local functionality with API Gateway & Open API
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GoodByeFunction.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 3000
        type: "aws_proxy"
      responses:
        '200':
          description: A 200 response.
          content:
            application/json:
              schema:
                type: object
        '400':
          description: bad input parameter
